name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps TCP port 5432 on service container to the host
          - 5432:5432
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/proto
      JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}
      CLIENT_ID_GITHUB: ${{ secrets.CLIENT_ID_GITHUB }}
      CLIENT_SECRET_GITHUB: ${{ secrets.CLIENT_SECRET_GITHUB }}
      REDIRECT_URI_GITHUB: ${{ secrets.REDIRECT_URI_GITHUB }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      JUDGE_API_URL: ${{ secrets.JUDGE_API_URL }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.13"
      - run: yarn run install
      - run: yarn run setup
      - run: cd backend && (yarn run test:dev & yarn run test)
      - run: cd frontend && yarn test
